import colors, { opacity } from "@/utils/colors";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: colors.white,
  },
  safeareaview: {
    backgroundColor: colors.black,
    display: "flex",
    flex: 1
  },
  content: {
    flex: 1,
    borderTopLeftRadius: 48,
    borderTopRightRadius: 48,
    backgroundColor: colors.white,
    display: "flex",
    flexDirection: "column",
    // justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 36,
    paddingBottom: 120,
    paddingLeft: 24,
    paddingRight: 24,
    gap: 18,
  },
  title: {
    padding: 24,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  titleText: {
    // position: "absolute",
    left: "50%",
    fontSize: 28,
    fontWeight: "600",
    color: colors.white,
  },
  statusBar: {
    backgroundColor: "black",
  },
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  body: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "lightgray",
  },
  text: {
    color: "black",
  },
  center: {
  },
  message: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    // backgroundColor: colors.black,
  },
  sender: {
    // display: "flex",
    // flexDirection: "row",
    // alignItems: "center",
    // justifyContent: "flex-end",
    fontSize: 12,
    fontWeight: "600",
    marginRight: 54,
    color: colors.black,
  },
  stack: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  time: {
    fontSize: 8,
    fontWeight: "400",
    color: colors.black,
  },
  msgContent: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 12,
    paddingBottom: 12,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    borderTopLeftRadius: 24,
    backgroundColor: colors.black,
    color: colors.white,
  },
  msgText: {
    color: colors.white,
    backgroundColor: colors.black,
    fontSize: 12,
    fontWeight: "600",
  },
  profile: {
    width: 48,
    height: 48,
    backgroundColor: colors.black,
    borderRadius: 24,
    transform: [{ translateY: -12 }],
  },
  textbox: {
    position: "absolute",
    bottom: 36,
    width: "100%",
    padding: 8,
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#F1F1F1",
    borderRadius: 24,
    justifyContent: "space-between",
    alignItems: "center",
  },
  send: {
    borderRadius: 24,
    backgroundColor: colors.black,
    width: 42,
    height: 42,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  input: {
    flex: 1,
    marginLeft: 24,
    fontSize: 18,
    color: colors.black,
  },
  textInput: {
    flex: 1,
    color: colors.black,
    paddingHorizontal: 16,
  },
  game: {
    position: "absolute",
    bottom: 120,
    width: "100%",
    height: 144,
    backgroundColor: "#F1F1F1",
    borderRadius: 24,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16
  },
  gameStatus: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.black,
  },
  gameStart: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: colors.black,
    borderRadius: 12,
  },
  gameStartText : {
    color: colors.white,
  },
  modal: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    backgroundColor: opacity(colors.black, 0.3),
    zIndex: 1,
    position: "absolute",
    top: 0,
    paddingHorizontal: 24,
  },
  modalBackground: {
    padding: 24,
    backgroundColor: colors.white,
    borderRadius: 24,
    width: "100%",
  },
  modalTitle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    // width: "100%"
  },
  modalTitleText: {
    color: colors.black,
    fontSize: 18,
    textAlign: "center",
    fontStyle: "normal",
    fontWeight: "600",
  },
  modalContent:{
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  name: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.black,
  },
  leftSide: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 12,
  },
  rightSide: {},
  arrived: {
    fontSize: 10,
    fontWeight: "500",
    color: colors.white,
    backgroundColor: "#76DF8D",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
  },
  mdcontent: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    width: "100%",
  },
  profiles: {
    width: 40,
    height: 40,
    borderRadius: 20,
  }
});