import colors, { opacity } from "@/utils/colors";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  top: {
    display: "flex",
    paddingVertical: 32,
    paddingHorizontal: 24,
    alignItems: "flex-start",
    gap: 10,
  },
  bottom: {
    display: "flex",
    paddingHorizontal: 24,
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    position: "absolute",
    bottom: 36,
    width: "100%",
  },
  next: {
    backgroundColor: colors.black,
    display: "flex",
    paddingVertical: 16,
    justifyContent: "center",
    gap: 24,
    alignItems: "center",
    alignSelf: "stretch",
    width: "100%",
    borderRadius: 12,
  },
  nextText: {
    color: colors.white,
    textAlign: "center",
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: "500",
  },
  circles: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  circle: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: opacity(colors.black, 0.2),
  },
  circleThis: {
    backgroundColor: colors.black,
  },
  middle: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 36,
    width: "100%",
    height: "60%",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  title: {
    color: colors.black,
    textAlign: "center",
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: "500",
  },
  input: {
    color: colors.black,
    fontSize: 14,
    fontStyle: "normal",
    fontWeight: "300",
    backgroundColor: colors.gray,
    paddingVertical: 12,
    paddingHorizontal: 24,
    width: "100%",
    borderRadius: 24,
  },
  picker: {
    color: colors.black,
    fontSize: 14,
    fontStyle: "normal",
    fontWeight: "300",
    paddingVertical: 12,
    width: "100%",
  },
  pickerP: {
    backgroundColor: colors.gray,
    color: colors.black,
    width: "100%",
    paddingHorizontal: 24,
    borderRadius: 24,
    overflow: "hidden",
  }
});