import colors, { opacity } from "@/utils/colors";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  warpper: {
    width: "100%",
    height: "100%",
    backgroundColor: colors.black,
  },
  container: {
    display: "flex",
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 32,
    alignItems: "flex-start",
    gap: 36,
  },
  top: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    alignSelf: "stretch",
    flexDirection: "row",
  },
  timeDiv: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  time: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "400",
    fontStyle: "normal",
  },
  timeData: {
    color: colors.white,
    fontSize: 18,
    fontWeight: "600",
    fontStyle: "normal",
  },
  titleDiv: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 4,
  },
  title:{
    color: colors.white,
    fontSize: 28,
    fontWeight: "600",
    fontStyle: "normal",
  },
  icons: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  ticket: {
    backgroundColor: colors.white,
    borderRadius: 16,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  ticketText: {
    color: colors.black,
    fontSize: 18,
    fontWeight: "700",
    fontStyle: "normal",
  },
  ticketText2: {
    color: colors.black,
    fontSize: 16,
    fontWeight: "400",
    fontStyle: "normal",
  },
  ticketLeft: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 14,
    padding: 24,
    width: "70%",

    borderColor: colors.gray,
    borderStyle: "dashed",
    borderRightWidth: 2,
  },
  ticketText3: {
    color: colors.black,
    fontSize: 16,
    fontWeight: "700",
    fontStyle: "normal",
  },
  ticketRight: {
    padding: 24,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    height: 140,
  },
  ticketImage: {
    width: 100,
    objectFit: "contain",
    height: 20,
  },
  rankingDiv: {
    display: "flex",
    flexDirection: "column",
    aliginItems: "flex-start",
    gap: 14,
    alignSelf: "stretch",
  },
  ranking: {
    color: colors.white,
    fontSize: 18,
    fontStyle: "normal",
    fontWeight: "600",
  },
  ranker: {
    width: "100%",
    backgroundColor: colors.white,
    borderRadius: 32,
    overflow: "visible",
  },
  rankerInner: {
    borderRadius: 32,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    height: 32,
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingHorizontal: 14,
    overflow: "visible",
    gap: 10,
  },
  rankerText: {
    color: colors.black,
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "600",
  },
  gameDiv: {
    padding: 36,
    backgroundColor: colors.white,
    borderRadius: 32,
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
  },
  gameTitle: {
    fontSize: 20,
    fontWeight: "600",
    fontStyle: "normal",
    color: colors.black,
  },
  ticketImage2: {
    width: 200,
    objectFit: "contain",
    height: 40,
  },
  gameCont1: {
    color: colors.black,
    fontSize: 14,
    fontWeight: "400",
    fontStyle: "normal",
    textAlign: "center",
  },
  gameCont2: {
    color: colors.black,
    fontSize: 20,
    fontWeight: "600",
    fontStyle: "normal",
    textAlign: "center",
  },
  gameButton: {
    width: "100%",
    borderRadius: 12,
    backgroundColor: colors.black,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: 24,
  },
  gameButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "600",
    fontStyle: "normal",
  },
  gameButtonText2: {
    textAlign: "center",
    width: "100%",
    color: opacity(colors.black, 0.3),
    fontSize: 16,
    fontWeight: "600",
    fontStyle: "normal",
  },
});